name: spark_connect
description: "A professional social media app built with Flutter and Supabase"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10
  google_fonts: ^6.2.1
  animated_bottom_navigation_bar: ^1.3.3
  lottie: ^3.1.2
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1

  # State Management & Navigation
  get: ^4.6.6

  # Backend & Database
  supabase_flutter: ^2.5.6

  # Authentication
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  crypto: ^3.0.3

  # Media & Camera
  image_picker: ^1.1.2
  video_player: ^2.8.6
  camera: ^0.10.5+9
  permission_handler: ^11.3.1

  # Storage & Files
  path_provider: ^2.1.3
  file_picker: ^8.0.3

  # Utils & Helpers
  intl: ^0.19.0
  uuid: ^4.4.0
  url_launcher: ^6.2.6
  share_plus: ^9.0.0
  timeago: ^3.6.1

  # Animations & Transitions
  flutter_animate: ^4.5.0
  page_transition: ^2.1.0

  # Network & HTTP
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/logos/
